<?php
/**
 * CheckDocumentBankAccountsOutputTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yousign API Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * Contact: support@yousign.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CheckDocumentBankAccountsOutputTest Class Doc Comment
 *
 * @category    Class
 * @description CheckDocumentBankAccountsOutput
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckDocumentBankAccountsOutputTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckDocumentBankAccountsOutput"
     */
    public function testCheckDocumentBankAccountsOutput()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "birth_name"
     */
    public function testPropertyBirthName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "extracted_iban"
     */
    public function testPropertyExtractedIban()
    {
    }

    /**
     * Test attribute "first_name_valid"
     */
    public function testPropertyFirstNameValid()
    {
    }

    /**
     * Test attribute "birth_name_valid"
     */
    public function testPropertyBirthNameValid()
    {
    }

    /**
     * Test attribute "last_name_valid"
     */
    public function testPropertyLastNameValid()
    {
    }

    /**
     * Test attribute "company_name_valid"
     */
    public function testPropertyCompanyNameValid()
    {
    }

    /**
     * Test attribute "iban_valid"
     */
    public function testPropertyIbanValid()
    {
    }
}
