<?php
/**
 * ConsentProcessValueApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YouSign\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yousign API Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * Contact: support@yousign.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YouSign\Client;

use YouSign\Client\Configuration;
use YouSign\Client\ApiException;
use YouSign\Client\ObjectSerializer;

/**
 * ConsentProcessValueApiTest Class Doc Comment
 *
 * @category Class
 * @package  YouSign\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConsentProcessValueApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for consentProcessValuesGet
     *
     * Get list of Consent Process Value.
     *
     */
    public function testConsentProcessValuesGet()
    {
    }

    /**
     * Test case for consentProcessValuesIdGet
     *
     * Get a Consent Process Value.
     *
     */
    public function testConsentProcessValuesIdGet()
    {
    }

    /**
     * Test case for consentProcessValuesPost
     *
     * Create a new Consent Process Value.
     *
     */
    public function testConsentProcessValuesPost()
    {
    }
}
