<?php
/**
 * FileObjectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YouSign\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yousign API Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * Contact: support@yousign.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YouSign\Client;

use YouSign\Client\Configuration;
use YouSign\Client\ApiException;
use YouSign\Client\ObjectSerializer;

/**
 * FileObjectApiTest Class Doc Comment
 *
 * @category Class
 * @package  YouSign\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileObjectApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for fileObjectsIdDelete
     *
     * Delete a File Object.
     *
     */
    public function testFileObjectsIdDelete()
    {
    }

    /**
     * Test case for fileObjectsIdGet
     *
     * Find a File Object by ID.
     *
     */
    public function testFileObjectsIdGet()
    {
    }

    /**
     * Test case for fileObjectsIdPut
     *
     * Update a File Object.
     *
     */
    public function testFileObjectsIdPut()
    {
    }

    /**
     * Test case for fileObjectsPost
     *
     * Create a new File Object.
     *
     */
    public function testFileObjectsPost()
    {
    }
}
