<?php
/**
 * MembersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yousign API Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * Contact: support@yousign.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MembersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MembersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for membersGet
     *
     * Get all Members.
     *
     */
    public function testMembersGet()
    {
    }

    /**
     * Test case for membersIdDelete
     *
     * Delete a Member.
     *
     */
    public function testMembersIdDelete()
    {
    }

    /**
     * Test case for membersIdProofGet
     *
     * Get a proof file of a Member.
     *
     */
    public function testMembersIdProofGet()
    {
    }

    /**
     * Test case for membersIdPut
     *
     * Edit a Member.
     *
     */
    public function testMembersIdPut()
    {
    }

    /**
     * Test case for membersPost
     *
     * Create a new Member.
     *
     */
    public function testMembersPost()
    {
    }
}
